baseURL = "https://edavis.github.io/"
languageCode = "en-us"
title = "Eric Davis"
theme = "sustain"
publishDir = "../pub/"
rssLimit = 25

[permalinks]
  blog = "/:year/:month/:day/:slug"

[params]
  author = "Eric Davis"
  description = "Personal homepage for Eric Davis"
  custom_css = ["css/overrides.css"]

[params.Social]
  Github = "edavis"
  Email = "circa1979@gmail.com"
  Twitter = "ejd215"
  Facebook = "ericdavis215"
  LinkedIn = "ericdavis215"
  StackOverflow = "users/3416550/edavis"

[[Menu.main]]
  name = "blog"
  identifier = "blog"
  weight = 0
  url = "/blog/"
